seed: 2
device: auto

airl:
  expert_path: ./RL/train_scripts/expert/expert_data.pkl
  pretrain_path: ./RL/train_scripts/checkpoints/pretrain/ppo_policy.zip
  min_expert_episodes: 30
  rounds: 35
  steps_per_round: 12000
  demo_batch_size: 512
  gen_replay_buffer_capacity: 2048
  gen_train_timesteps: 500
  n_disc_updates_per_round: 3
  disc_lr: 0.00005
  gen_lr: 0.00005
  reward_dir: ./RL/train_scripts/checkpoints/airl/reward
  policy_dir: ./RL/train_scripts/checkpoints/airl/policy

policy:
  policy_type: custom
  features_dim: 96
  log_std_init: -2.7

vec_env:
  n_envs: 1
  gui: false

logging:
  tensorboard_dir: ./RL/train_scripts/logs/airl/
